/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartTodayRouteImport } from './routes/start-today'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyMattersRouteImport } from './routes/privacy-matters'
import { Route as PrivacyArticlesRouteImport } from './routes/privacy-articles'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OurServiceRouteImport } from './routes/our-service'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as EncryptedMessagingRouteImport } from './routes/encrypted-messaging'
import { Route as EncryptedChatRouteImport } from './routes/encrypted-chat'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StartTodayRoute = StartTodayRouteImport.update({
  id: '/start-today',
  path: '/start-today',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyMattersRoute = PrivacyMattersRouteImport.update({
  id: '/privacy-matters',
  path: '/privacy-matters',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyArticlesRoute = PrivacyArticlesRouteImport.update({
  id: '/privacy-articles',
  path: '/privacy-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OurServiceRoute = OurServiceRouteImport.update({
  id: '/our-service',
  path: '/our-service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptedMessagingRoute = EncryptedMessagingRouteImport.update({
  id: '/encrypted-messaging',
  path: '/encrypted-messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const EncryptedChatRoute = EncryptedChatRouteImport.update({
  id: '/encrypted-chat',
  path: '/encrypted-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/encrypted-chat': typeof EncryptedChatRoute
  '/encrypted-messaging': typeof EncryptedMessagingRoute
  '/legal': typeof LegalRoute
  '/our-service': typeof OurServiceRoute
  '/packages': typeof PackagesRoute
  '/privacy-articles': typeof PrivacyArticlesRoute
  '/privacy-matters': typeof PrivacyMattersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-today': typeof StartTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/encrypted-chat': typeof EncryptedChatRoute
  '/encrypted-messaging': typeof EncryptedMessagingRoute
  '/legal': typeof LegalRoute
  '/our-service': typeof OurServiceRoute
  '/packages': typeof PackagesRoute
  '/privacy-articles': typeof PrivacyArticlesRoute
  '/privacy-matters': typeof PrivacyMattersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-today': typeof StartTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buy': typeof BuyRoute
  '/encrypted-chat': typeof EncryptedChatRoute
  '/encrypted-messaging': typeof EncryptedMessagingRoute
  '/legal': typeof LegalRoute
  '/our-service': typeof OurServiceRoute
  '/packages': typeof PackagesRoute
  '/privacy-articles': typeof PrivacyArticlesRoute
  '/privacy-matters': typeof PrivacyMattersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start-today': typeof StartTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buy'
    | '/encrypted-chat'
    | '/encrypted-messaging'
    | '/legal'
    | '/our-service'
    | '/packages'
    | '/privacy-articles'
    | '/privacy-matters'
    | '/sitemap.xml'
    | '/start-today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buy'
    | '/encrypted-chat'
    | '/encrypted-messaging'
    | '/legal'
    | '/our-service'
    | '/packages'
    | '/privacy-articles'
    | '/privacy-matters'
    | '/sitemap.xml'
    | '/start-today'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buy'
    | '/encrypted-chat'
    | '/encrypted-messaging'
    | '/legal'
    | '/our-service'
    | '/packages'
    | '/privacy-articles'
    | '/privacy-matters'
    | '/sitemap.xml'
    | '/start-today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyRoute: typeof BuyRoute
  EncryptedChatRoute: typeof EncryptedChatRoute
  EncryptedMessagingRoute: typeof EncryptedMessagingRoute
  LegalRoute: typeof LegalRoute
  OurServiceRoute: typeof OurServiceRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyArticlesRoute: typeof PrivacyArticlesRoute
  PrivacyMattersRoute: typeof PrivacyMattersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartTodayRoute: typeof StartTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-today': {
      id: '/start-today'
      path: '/start-today'
      fullPath: '/start-today'
      preLoaderRoute: typeof StartTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-matters': {
      id: '/privacy-matters'
      path: '/privacy-matters'
      fullPath: '/privacy-matters'
      preLoaderRoute: typeof PrivacyMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-articles': {
      id: '/privacy-articles'
      path: '/privacy-articles'
      fullPath: '/privacy-articles'
      preLoaderRoute: typeof PrivacyArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-service': {
      id: '/our-service'
      path: '/our-service'
      fullPath: '/our-service'
      preLoaderRoute: typeof OurServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypted-messaging': {
      id: '/encrypted-messaging'
      path: '/encrypted-messaging'
      fullPath: '/encrypted-messaging'
      preLoaderRoute: typeof EncryptedMessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encrypted-chat': {
      id: '/encrypted-chat'
      path: '/encrypted-chat'
      fullPath: '/encrypted-chat'
      preLoaderRoute: typeof EncryptedChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyRoute: BuyRoute,
  EncryptedChatRoute: EncryptedChatRoute,
  EncryptedMessagingRoute: EncryptedMessagingRoute,
  LegalRoute: LegalRoute,
  OurServiceRoute: OurServiceRoute,
  PackagesRoute: PackagesRoute,
  PrivacyArticlesRoute: PrivacyArticlesRoute,
  PrivacyMattersRoute: PrivacyMattersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartTodayRoute: StartTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
